-- INDEX
-- 테이블에 있는 데이터를 빠르게 검색하기 위한 용도로 나온 데이터베이스 객체
-- 테이블에 하나 이상의 컬럼으로 인덱스를 만들 수 있음
-- 오라클에서는 기본적으로 테이블 기본키로 인덱스가 설정되어 있음.
-- 인덱스는 제약 조건이 아니다, 그래서 다른 테이블에서 외래키로 사용이 불가능 하다.
-- 생성한 모든 인덱스 객체를 조회
SELECT * FROM USER_INDEXES;

SELECT * FROM PERSON;
-- CREATE [UNIQUE] INDEX 인덱스명 ON 테이블(컬럼1, 컬럼2, ....);
CREATE INDEX IDX_PERSON_PNAME ON PERSON(PNAME);
DROP INDEX IDX_PERSON_PNAME;
CREATE UNIQUE INDEX IDX_PERSON_PNAME ON PERSON(PNAME);
DELETE FROM PERSON WHERE PID = 20;

-- 외래키 관련 내용
CREATE TABLE DEPT (
    DEPTNO NUMBER,
    DNAME VARCHAR2(100)
);

CREATE TABLE EMP (
    EMPNO NUMBER,
    ENAME VARCHAR2(100),
    DEPTNO NUMBER
);
-- DEPT의 DEPTNO에 UNIQUE 적용해서 INDEX 지정
CREATE UNIQUE INDEX IDX_DEPT_DEPTNO ON DEPT(DEPTNO);
-- EMP 테이블에서 DEPTNO를 외래키 지정 DEPT 테이블의 DEPTNO
ALTER TABLE EMP ADD CONSTRAINT FK_EMP_DEPTNO FOREIGN KEY(DEPTNO)
REFERENCES DEPT(DEPTNO);
-- 테이블 컬럼에 제약조건으로 UNIQUE 적용
ALTER TABLE DEPT ADD CONSTRAINT UQ_DEPTNO UNIQUE(DEPTNO);

DROP TABLE EMP;
DROP TABLE DEPT;
DROP INDEX IDX_DEPT_DEPTNO;

INSERT INTO DEPT VALUES(1,'테스트');
SELECT * FROM DEPT;
DELETE FROM DEPT;