-- 제약조건
SELECT * FROM USER_CONSTRAINTS;
-- 기본키
DROP TABLE PERSON;
-- 1. CONSTRAINT 제약조건명 PRIMARY KEY(컬럼) <-- 테이블 생성시
CREATE TABLE PERSON(	
    PID CHAR(4),
    PNAME VARCHAR2(30 BYTE), 
    AGE NUMBER(3,0),
    CONSTRAINT PK_PID PRIMARY KEY(PID)
);
-- 2. ALTER TABLE 테이블명 ADD CONSTRAINT 제약조건명 PRIMARY KEY(컬럼); <-- 테이블 생성 후
CREATE TABLE PERSON(	
    PID CHAR(4),
    PNAME VARCHAR2(30 BYTE), 
    AGE NUMBER(3,0)
);
ALTER TABLE PERSON ADD CONSTRAINT PK_PID PRIMARY KEY(PID);
--샘플데이터
INSERT INTO PERSON VALUES('0001','홍길동',20);
INSERT INTO PERSON VALUES('0002','김길동',30);
INSERT INTO PERSON VALUES('0003','이길동',40);
INSERT INTO PERSON VALUES('0004','박길동',50);

DROP TABLE PERSON_ORDER;
CREATE TABLE PERSON_ORDER(
	P_ORDER_NO NUMBER(5),
	P_ORDER_MEMO VARCHAR2(300),
	PID CHAR(4)
);
--PERSON_ORDER에 P_ORDER_NO를 기본키로 작성
ALTER TABLE PERSON_ORDER ADD CONSTRAINT PERSON_ORDER_PO_NO_PK
PRIMARY KEY(P_ORDER_NO);
-- PERSON_ORDER에 PID를 외래키로 설정, PERSON 테이블의 PID와 연결
ALTER TABLE PERSON_ORDER ADD CONSTRAINT PERSON_ORDER_FK_PID
FOREIGN KEY(PID) REFERENCES PERSON(PID);


INSERT INTO PERSON_ORDER VALUES(1, '지시 내용', '0001');
INSERT INTO PERSON_ORDER VALUES(2, '지시 내용', '0002');
INSERT INTO PERSON_ORDER VALUES(3, '지시 내용', '0003');
INSERT INTO PERSON_ORDER VALUES(4, '지시 내용', '0005');

-- 외래키

-- 컬럼 조건(CHECK)

-- Sub Query(서브 쿼리)