-- 제약조건
SELECT * FROM USER_CONSTRAINTS;
-- 기본키
DROP TABLE PERSON;
-- 1. CONSTRAINT 제약조건명 PRIMARY KEY(컬럼) <-- 테이블 생성시
CREATE TABLE PERSON(	
    PID CHAR(4),
    PNAME VARCHAR2(30 BYTE), 
    AGE NUMBER(3,0),
    CONSTRAINT PK_PID PRIMARY KEY(PID)
);
-- 2. ALTER TABLE 테이블명 ADD CONSTRAINT 제약조건명 PRIMARY KEY(컬럼); <-- 테이블 생성 후
CREATE TABLE PERSON(	
    PID CHAR(4),
    PNAME VARCHAR2(30 BYTE), 
    AGE NUMBER(3,0)
);
ALTER TABLE PERSON ADD CONSTRAINT PK_PID PRIMARY KEY(PID);
--샘플데이터
INSERT INTO PERSON VALUES('0001','홍길동',20);
INSERT INTO PERSON VALUES('0002','김길동',30);
INSERT INTO PERSON VALUES('0003','이길동',40);
INSERT INTO PERSON VALUES('0004','박길동',50);

-- 외래키

-- 컬럼 조건(CHECK)

-- Sub Query(서브 쿼리)