-- INDEX
-- 테이블에 있는 데이터를 빠르게 검색하기 위한 용도로 나온 데이터베이스 객체
-- 테이블에 하나 이상의 컬럼으로 인덱스를 만들 수 있음
-- 오라클에서는 기본적으로 테이블 기본키로 인덱스가 설정되어 있음.
-- 인덱스는 제약 조건이 아니다, 그래서 다른 테이블에서 외래키로 사용이 불가능 하다.
-- 생성한 모든 인덱스 객체를 조회
SELECT * FROM USER_INDEXES;

SELECT * FROM PERSON;
-- CREATE [UNIQUE] INDEX 인덱스명 ON 테이블(컬럼1, 컬럼2, ....);
CREATE INDEX IDX_PERSON_PNAME ON PERSON(PNAME);
DROP INDEX IDX_PERSON_PNAME;
CREATE UNIQUE INDEX IDX_PERSON_PNAME ON PERSON(PNAME);
DELETE FROM PERSON WHERE PID = 20;

-- 외래키 관련 내용
CREATE TABLE DEPT (
    DEPTNO NUMBER,
    DNAME VARCHAR2(100)
);

CREATE TABLE EMP (
    EMPNO NUMBER,
    ENAME VARCHAR2(100),
    DEPTNO NUMBER
);
-- DEPT의 DEPTNO에 UNIQUE 적용해서 INDEX 지정
CREATE UNIQUE INDEX IDX_DEPT_DEPTNO ON DEPT(DEPTNO);
-- EMP 테이블에서 DEPTNO를 외래키 지정 DEPT 테이블의 DEPTNO
ALTER TABLE EMP ADD CONSTRAINT FK_EMP_DEPTNO FOREIGN KEY(DEPTNO)
REFERENCES DEPT(DEPTNO);
-- 테이블 컬럼에 제약조건으로 UNIQUE 적용
ALTER TABLE DEPT ADD CONSTRAINT UQ_DEPTNO UNIQUE(DEPTNO);

DROP TABLE EMP;
DROP TABLE DEPT;
DROP INDEX IDX_DEPT_DEPTNO;

INSERT INTO DEPT VALUES(1,'테스트');
SELECT * FROM DEPT;
DELETE FROM DEPT;

-- CAR_SELL 테이블에 판매날짜(CAR_SELL_DATE)에 인덱스 적용
CREATE INDEX IDX_CAR_SELL_DATE ON CAR_SELL(CAR_SELL_DATE);
-- 리빌딩
-- 데이터를 추가 삭제 수정등의 작업을 하다보면 트리가 한쪽로 치우쳐지는 현상이 나기 때문
ALTER INDEX IDX_CAR_SELL_DATE REBUILD;

-- SEQUENCE
-- 자동으로 증가하는 순번을 반환하는 데이터베이스 객체
CREATE SEQUENCE SEQ_NO;
DROP SEQUENCE SEQ_NO;

-- 아무런 옵션 없이 시퀸스 만들면 아래와 같은 형태로 만들어줌
CREATE SEQUENCE seq_example
  START WITH     1
  INCREMENT BY   1
  MAXVALUE       999999999999999999999999999
  MINVALUE       1
  NOCYCLE
  CACHE          20
  NOORDER;


-- 다음 번호 뽑기
SELECT SEQ_NO.NEXTVAL FROM DUAL;
-- 현재 번호 뽑기
SELECT SEQ_NO.CURRVAL FROM DUAL;
-- 생성된 시퀸스 목록
SELECT * FROM USER_SEQUENCES;

CREATE SEQUENCE TEST_SEQ
INCREMENT BY 2
START WITH 4
MINVALUE 4 -- NOMINVALUE
MAXVALUE 10 -- NOMAXVALUE
CYCLE -- NOCYCLE
CACHE 2; -- NOCACHE
DROP SEQUENCE TEST_SEQ;

CREATE SEQUENCE TEST_SEQ
INCREMENT BY 2
START WITH 4
MINVALUE 4 -- NOMINVALUE
MAXVALUE 10 -- NOMAXVALUE
CACHE 2; -- NOCACHE

CREATE SEQUENCE TEST_SEQ
INCREMENT BY 2
START WITH 4
NOMINVALUE
MAXVALUE 10 -- NOMAXVALUE
CACHE 2; -- NOCACHE

CREATE SEQUENCE TEST_SEQ
INCREMENT BY -1
NOMINVALUE
NOMAXVALUE
CACHE 2; -- NOCACHE

-- INCREMENT > 0 : NOMAXVALUE - 9999999999..., NOMINVALUE - 1
-- INCREMENT < 0 : NOMAXVALUE - -1, NOMINVALUE - -9999999999...

SELECT TEST_SEQ.NEXTVAL FROM DUAL;
-- 18버전부터 지원
ALTER SEQUENCE TEST_SEQ RESTART START WITH 4;

CREATE SEQUENCE TEST_SEQ
INCREMENT BY 1
START WITH -4
MINVALUE -4
MAXVALUE 10 -- NOMAXVALUE
CACHE 2; -- NOCACHE

--문제 1
--기본 시퀀스 생성
--시퀀스 이름: SEQ_EMP_ID
--시작 값: 1
--최대 값: 9999
--증가 값: 1
--캐시 값: 20

--문제2
--시퀀스 이름: SEQ_DEPT_ID
--시작 값: 100
--최대 값: 110
--최소 값: 100
--증가 값: 1
--순환(CYCLE) 사용

--시퀀스 이름: SEQ_ORDER_NO
--시작 값: 1000
--최소 값: 500
--감소 값: 10
--순환(CYCLE) 미사용
