-- 조인(JOIN)
-- 여러개 테이블에서 필요한 데이터를 조회하기 위해
-- 테이블을 결합해서 조회하기 위한 연산
-- 조인을 할려면 테이블끼리 연결 될 수 있는 동일한 데이터를 가지고 있는 컬럼이 있어야함
CREATE TABLE A(
	CODE CHAR(1),
	VAL NUMBER(1)
);
CREATE TABLE B(
	CODE CHAR(1),
	UNIT CHAR(1)
);
INSERT INTO A VALUES('A',1);
INSERT INTO A VALUES('B',2);
INSERT INTO A VALUES('C',3);
INSERT INTO A VALUES('D',4);

INSERT INTO B VALUES('A','+');
INSERT INTO B VALUES('B','-');
INSERT INTO B VALUES('C','*');
INSERT INTO B VALUES('F','/');

SELECT * FROM A;
SELECT * FROM B;

-- 동일 조인
-- 특정 컬럼을 선택해서 같은 값을 기준으로 결합
SELECT A.CODE, A.VAL, B.CODE, B.UNIT
FROM A, B
WHERE A.CODE = B.CODE;
-- INNER JOIN
-- 조인 조건을 만족하는 모든 행을 결함
SELECT A.CODE, A.VAL, B.CODE, B.UNIT
FROM A INNER JOIN B ON A.CODE = B.CODE;
SELECT A.CODE, A.VAL, B.CODE, B.UNIT
FROM A JOIN B ON A.CODE = B.CODE;

SELECT A.CODE, A.VAL, B.CODE, B.UNIT
FROM A INNER JOIN B ON A.CODE <> B.CODE;
-- NATURAL JOIN
-- 자연 조인
-- 자동으로 똑같은 컬럼을 찾아서 조인하고, 중복된 컬럼은 제거해서 조회
SELECT * FROM A NATURAL JOIN B;

-- CROSS JOIN
-- 교차 조인
-- 두 테이블의 모든 조합을 조회
SELECT * FROM A CROSS JOIN B;

-- 학생 테이블에 있는 학과명을 중복된 내용을 제외하고 조회
SELECT 
    'M' || TO_CHAR(ROW_NUMBER() OVER(ORDER BY MNAME),'FM00') AS MNO, 
    MNAME 
FROM 
    (SELECT DISTINCT MNAME FROM STUDENT);

CREATE TABLE MAJOR
AS
SELECT 
    'M' || TO_CHAR(ROW_NUMBER() OVER(ORDER BY MNAME),'FM00') AS MNO, 
    MNAME 
FROM 
    (SELECT DISTINCT MNAME FROM STUDENT);

-- 학생 테이블에 학과 번호 컬럼을 추가
ALTER TABLE STUDENT ADD MNO VARCHAR2(4);

-- 학생 테이블에 학과 번호를 업데이트
UPDATE STUDENT S SET S.MNO = 
(SELECT M.MNO FROM MAJOR M WHERE S.MNAME = M.MNAME);

SELECT * FROM STUDENT;
-- 학생 테이블에서 학과명 컬럼을 제거
ALTER TABLE STUDENT DROP COLUMN MNAME;

-- 학생 정보 조회시
-- 학번 이름 학과명 평점을 조회
SELECT S.SNO, S.SNAME, M.MNAME, S.SCORE
FROM STUDENT S INNER JOIN MAJOR M ON S.MNO = M.MNO;

-- CAR 테이블에 있는 제조사 이름을 제조사 테이블로 분리
-- 제조사 CAR_MAKER(CM_ID, CM_NAME)
-- 1. CAR 테이블에서 제조사 이름만 조회, 중복된 내용 제거
SELECT DISTINCT MAKER FROM CAR;
-- 2. 1번 결과를 가지고 제조사 아이디값 생성 제조사 첫글자 + 숫자3자리
--    숫자 3자리는 행번호
SELECT
    SUBSTR(MAKER,1,1) ||
    TO_CHAR(ROW_NUMBER() OVER(ORDER BY MAKER),'FM000') AS CM_ID,
    MAKER AS CM_NAME
FROM
(SELECT DISTINCT MAKER FROM CAR);
-- 3. CAR_MAKER 테이블 생성
CREATE TABLE CAR_MAKER
AS
SELECT
    SUBSTR(MAKER,1,1) ||
    TO_CHAR(ROW_NUMBER() OVER(ORDER BY MAKER),'FM000') AS CM_ID,
    MAKER AS CM_NAME
FROM
(SELECT DISTINCT MAKER FROM CAR);

SELECT * FROM CAR_MAKER;

-- CAR 테이블에 CM_ID 컬럼 추가
ALTER TABLE CAR ADD CM_ID VARCHAR2(8);
-- CAR 테이블에 CM_ID 값을 업데이트
UPDATE CAR C 
SET 
C.CM_ID = 
(SELECT CM.CM_ID FROM CAR_MAKER CM WHERE C.MAKER = CM.CM_NAME);
SELECT * FROM CAR;
-- CAR 테이블에 MAKER 컬럼을 제거
ALTER TABLE CAR DROP COLUMN MAKER;

-- 자동차 정보 조회시
--  자동차모델 번호, 자동차 모델명, 제조년도, 제조사명, 금액
SELECT C.ID, C.CNAME, C.MYEAR, CM.CM_NAME, C.PRICE
FROM CAR C 
INNER JOIN CAR_MAKER CM ON C.CM_ID = CM.CM_ID;

SELECT SNO FROM STUDENT;
--장학금 테이블
CREATE TABLE STUDENT_SCHOLARSHIP(
    SSNO NUMBER,
    SNO CHAR(8),
    MONEY NUMBER
);

SELECT * FROM STUDENT_SCHOLARSHIP;

-- 장학금을 받는 학생 정보만 조회
-- 학번, 이름, 학과명, 장학금 금액
SELECT S.SNO, S.SNAME, M.MNAME, SS.MONEY
FROM
    MAJOR M 
    INNER JOIN STUDENT S ON M.MNO = S.MNO
    INNER JOIN STUDENT_SCHOLARSHIP SS ON S.SNO = SS.SNO;

-- 제조사별 자동차 개수를 조회
SELECT CM.CM_NAME, COUNT(*)
FROM CAR_MAKER CM INNER JOIN CAR C ON CM.CM_ID = C.CM_ID
GROUP BY CM.CM_NAME;

SELECT DISTINCT CM.CM_NAME, COUNT(*) OVER(PARTITION BY CM.CM_NAME)
FROM CAR_MAKER CM INNER JOIN CAR C ON CM.CM_ID = C.CM_ID;

-- 제조사별, 출시연도별 자동차 개수를 조회
SELECT CM.CM_NAME, C.MYEAR, COUNT(*)
FROM CAR_MAKER CM INNER JOIN CAR C ON CM.CM_ID = C.CM_ID
GROUP BY CM.CM_NAME, C.MYEAR;

SELECT DISTINCT 
    CM.CM_NAME, C.MYEAR,
    COUNT(*) OVER(PARTITION BY CM.CM_NAME, C.MYEAR)
FROM CAR_MAKER CM INNER JOIN CAR C ON CM.CM_ID = C.CM_ID;

-- 외부 조인(Outer JOIN)
-- 조건에 맞지 않는 행도 결과에 포함 시킬때 사용하는 조인
-- 조건에 맞지 않는 행은 NULL값으로 나옴
SELECT A.*, B.*
FROM A LEFT OUTER JOIN B ON A.CODE = B.CODE;
-- 오라클에서만 됨.
SELECT A.*, B.*
FROM A , B
WHERE A.CODE = B.CODE(+); 

SELECT A.*, B.*
FROM A RIGHT OUTER JOIN B ON A.CODE = B.CODE;

select * from MAJOR;

--학과 테이블 데이터를 2건 추가
INSERT INTO MAJOR VALUES('A09', '국어국문학과');
INSERT INTO MAJOR VALUES('B02', '생활체육학과');
INSERT INTO MAJOR VALUES('C03', '게임학과');

-- 학생정보 조회시, 학번, 이름, 학과명, 평점을 조회
SELECT S.SNO, S.SNAME, M.MNAME, S.SCORE
FROM STUDENT S INNER JOIN MAJOR M ON S.MNO = M.MNO;
-- 학생 정보 조회시 연결되지 않은 학과명도 조회
SELECT S.SNO, S.SNAME, M.MNAME, S.SCORE
FROM STUDENT S RIGHT OUTER JOIN MAJOR M ON S.MNO = M.MNO;
-- 학생이 한명도 없는 학과를 조회
-- 일치하지 않는 데이터를 조회 --> 불일치 쿼리
-- 학과번호, 학과명 만 조회
SELECT M.MNO, M.MNAME
FROM STUDENT S RIGHT OUTER JOIN MAJOR M ON S.MNO = M.MNO
WHERE S.SNO IS NULL;

SELECT M.MNO, M.MNAME
FROM MAJOR M LEFT OUTER JOIN STUDENT S ON M.MNO = S.MNO
WHERE S.SNO IS NULL;

-- 장학금을 받지 못하는 학생들을 조회
-- 학번, 이름, 학과명, 평점
SELECT S.SNO, S.SNAME, S.SCORE, M.MNAME
FROM STUDENT S 
    LEFT OUTER JOIN STUDENT_SCHOLARSHIP SS ON S.SNO = SS.SNO
    INNER JOIN MAJOR M ON S.MNO = M.MNO
WHERE SS.SNO IS NULL;

-- 학과별로 장학금을 받은 학생들의 학과별, 성별을 기준으로 인원수, 최대 평점, 최저 평점
-- 학과명, 성별, 인원수, 최대평점, 최저평점
SELECT M.MNAME, S.GENDER, COUNT(*), MAX(SCORE), MIN(SCORE)
FROM STUDENT S INNER JOIN MAJOR M ON S.MNO = M.MNO
INNER JOIN STUDENT_SCHOLARSHIP SS ON S.SNO = SS.SNO
GROUP BY M.MNAME, S.GENDER;

-- 학과별로 장학금을 못받은 학생들 숫자를 조회
-- 학과명, 학생수 만 출력
SELECT M.MNAME, COUNT(*)
FROM STUDENT S INNER JOIN MAJOR M ON S.MNO = M.MNO
LEFT OUTER JOIN STUDENT_SCHOLARSHIP SS ON S.SNO = SS.SNO
WHERE SS.SNO IS NULL
GROUP BY M.MNAME;

-- 자동차 판매 테이블
CREATE TABLE CAR_SELL(
    CAR_SELL_NO NUMBER PRIMARY KEY,
    ID VARCHAR2(10),
    CAR_SELL_EA NUMBER(3),
    CAR_SELL_PRICE NUMBER(10),
    CAR_SELL_DATE DATE DEFAULT SYSDATE
);

SELECT count(*) FROM CAR_SELL;

--자동차 판매 정보 조회
--판매 번호, 판매된 모델명, 판매일, 판매개수, 판매금액
SELECT 
    CS.CAR_SELL_NO, S.CNAME, 
    CS.CAR_SELL_DATE, CS.CAR_SELL_EA,
    CS.CAR_SELL_PRICE
FROM CAR S INNER JOIN CAR_SELL CS ON S.ID = CS.ID;
--한번도 판매되지 않은 자동차 목록 조회
--자동차 번호, 자동차 모델명, 제조사명, 제조년도, 금액
SELECT 
    C.ID, C.CNAME, CM.CM_NAME, C.MYEAR, C.PRICE
FROM CAR C INNER JOIN CAR_MAKER CM ON C.CM_ID = CM.CM_ID
LEFT OUTER JOIN CAR_SELL CS ON C.ID = CS.ID
WHERE CS.CAR_SELL_NO IS NULL;

--판매 연도별, 제조사별, 판매 대수 총합, 판매금액 총합, 판매금액 평균을 조회
SELECT TO_CHAR(CS.CAR_SELL_DATE,'YYYY') AS SELL_YEAR, CM.CM_NAME, 
    SUM(CS.CAR_SELL_EA) AS TOTAL_EA,
    SUM(CS.CAR_SELL_PRICE) AS TOTAL_PRICE,
    CEIL(AVG(CS.CAR_SELL_PRICE)) AS AVG_PRICE
FROM CAR C INNER JOIN CAR_MAKER CM ON C.CM_ID = CM.CM_ID
INNER JOIN CAR_SELL CS ON C.ID = CS.ID
GROUP BY TO_CHAR(CS.CAR_SELL_DATE,'YYYY'), CM.CM_NAME;

--판매 연도/월별, 제조사별, 판매 대수 총합, 판매금액 총합, 판매금액 평균을 조회

--판매 연도/분기, 판매 대수 총합, 판매금액 총합, 판매금액 평균을 조회
